import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  GENERATED_MARKER,
  syncCodexConfig,
  validatePortableSharedConfig,
} from '../lib/codex-config-sync.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function parseToml(content) {
  const result = {};
  let current = result;

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) {
      continue;
    }

    const tableMatch = line.match(/^\[([^\]]+)\]$/);
    if (tableMatch) {
      current = result;
      for (const segment of tableMatch[1].split('.')) {
        current[segment] ??= {};
        current = current[segment];
      }
      continue;
    }

    const [rawKey, ...rawValueParts] = line.split('=');
    const key = rawKey.trim();
    const rawValue = rawValueParts.join('=').trim();
    if (rawValue === 'true' || rawValue === 'false') {
      current[key] = rawValue === 'true';
    } else if (/^".*"$/.test(rawValue)) {
      current[key] = JSON.parse(rawValue);
    } else {
      current[key] = rawValue;
    }
  }

  return result;
}

async function tempConfigPaths() {
  const root = await mkdtemp(path.join(os.tmpdir(), 'codex-config-sync-'));
  const codexDir = path.join(root, '.codex');
  await mkdir(codexDir, { recursive: true });
  return {
    codexDir,
    localPath: path.join(codexDir, 'config.local.toml'),
    outputPath: path.join(codexDir, 'config.toml'),
    root,
    sharedPath: path.join(codexDir, 'config.shared.toml'),
  };
}

async function sync(paths) {
  return syncCodexConfig({ ...paths, parseToml });
}

describe('lib/codex-config-sync', () => {
  it('should accept the repo-owned shared Codex config', async () => {
    const sharedConfigPath = path.join(REPO_ROOT, 'dotfiles', 'ai', '.codex', 'config.shared.toml');
    const sharedConfig = parseToml(await readFile(sharedConfigPath, 'utf8'));

    validatePortableSharedConfig(sharedConfig, sharedConfigPath);
    assert.deepEqual(sharedConfig, {
      commit_attribution: '',
      features: {
        fast_mode: true,
        memories: true,
        multi_agent: true,
      },
      file_opener: 'vscode',
      memories: {
        disable_on_external_context: true,
      },
      model: 'gpt-5.5',
      model_reasoning_effort: 'xhigh',
      personality: 'pragmatic',
      service_tier: 'fast',
    });
  });

  it('should generate config from shared settings only', async () => {
    const paths = await tempConfigPaths();
    await writeFile(paths.sharedPath, 'personality = "pragmatic"\n\n[features]\nmemories = true\n');

    const result = await sync(paths);
    const content = await readFile(paths.outputPath, 'utf8');

    assert.equal(result.migratedLocal, false);
    assert.match(content, new RegExp(`^# ${GENERATED_MARKER}`));
    assert.match(content, /personality = "pragmatic"/);
    assert.match(content, /\[features\]\nmemories = true/);
  });

  it('should let local config override shared defaults', async () => {
    const paths = await tempConfigPaths();
    await writeFile(
      paths.sharedPath,
      'personality = "pragmatic"\n\n[features]\nmemories = true\nmulti_agent = true\n',
    );
    await writeFile(paths.localPath, '[features]\nmulti_agent = false\n');

    await sync(paths);

    assert.equal(
      await readFile(paths.outputPath, 'utf8'),
      [
        `# ${GENERATED_MARKER}`,
        '# Do not edit this file directly. Edit config.shared.toml or config.local.toml instead.',
        '',
        'personality = "pragmatic"',
        '',
        '[features]',
        'memories = true',
        'multi_agent = false',
        '',
      ].join('\n'),
    );
  });

  it('should migrate unmanaged config.toml to local config on first run', async () => {
    const paths = await tempConfigPaths();
    await writeFile(paths.sharedPath, 'personality = "pragmatic"\n');
    await writeFile(paths.outputPath, 'model = "local-machine"\n');

    const result = await sync(paths);

    assert.equal(result.migratedLocal, true);
    assert.equal(await readFile(paths.localPath, 'utf8'), 'model = "local-machine"\n');
    assert.match(await readFile(paths.outputPath, 'utf8'), /model = "local-machine"/);
  });

  it('should overwrite generated config.toml', async () => {
    const paths = await tempConfigPaths();
    await writeFile(paths.sharedPath, 'personality = "pragmatic"\n');
    await writeFile(paths.outputPath, `# ${GENERATED_MARKER}\npersonality = "old"\n`);

    await sync(paths);

    assert.match(await readFile(paths.outputPath, 'utf8'), /personality = "pragmatic"/);
  });

  it('should reject unmanaged output when local config already exists', async () => {
    const paths = await tempConfigPaths();
    await writeFile(paths.sharedPath, 'personality = "pragmatic"\n');
    await writeFile(paths.localPath, 'model = "local"\n');
    await writeFile(paths.outputPath, 'model = "unmanaged"\n');

    await assert.rejects(sync(paths), /is not generated and .*config\.local\.toml already exists/);
  });

  it('should reject missing shared config', async () => {
    const paths = await tempConfigPaths();

    await assert.rejects(sync(paths), /Missing required Codex config fragment/);
  });

  it('should reject forbidden machine-specific shared keys and local paths', () => {
    assert.throws(
      () =>
        validatePortableSharedConfig(
          {
            auth: 'token',
            features: {
              plugin_path: '/Users/emori/plugin',
            },
            marketplaces: ['tanaabstore'],
            notify: ['osascript'],
            projects: {
              '/Users/emori/tanaab/emori': {
                trust_level: 'trusted',
              },
            },
          },
          'shared.toml',
        ),
      /shared\.toml must contain only portable global Codex settings[\s\S]*auth is machine-specific[\s\S]*plugin_path is machine-specific[\s\S]*plugin_path contains a local path[\s\S]*marketplaces is machine-specific[\s\S]*notify is machine-specific[\s\S]*projects is machine-specific[\s\S]*\/Users\/emori\/tanaab\/emori uses a local path key/,
    );
  });

  it('should write generated config with private file mode', async () => {
    const paths = await tempConfigPaths();
    await writeFile(paths.sharedPath, 'personality = "pragmatic"\n');

    await sync(paths);

    assert.equal((await stat(paths.outputPath)).mode & 0o777, 0o600);
  });
});
